import { Image, Space } from "@mantine/core"
import NavLink from "./NavLink"
import Head from "next/head"

type Props = {
    page: string,
    children: JSX.Element
}

const Layout: React.FC<Props> = ({page, children}) => {



    var pages = {
        "home":"/",
        "rules":"/rules",
        "news":"https://google.com",
        "support":"https://google.com"
    }

    var links = []

    for(const [name, url] of Object.entries(pages)){
        links.push(<>
            <NavLink name={name} link={url} active={page.toUpperCase()==name.toUpperCase()}/>      
            <Space w="xl" />          
        </>)
    }

    return (
        <>
        <Head>
        <title>{page} | Slax Network</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div style={{
        "backgroundImage":"url('/minecraft.png')",
        "backgroundSize":"cover",
        "height": "100vh",
        "width": "100vw",
        "marginTop": "0",
      }}>
        <div style={{
          "height": "100vh",
          "width": "100vw",
          "marginTop": "0",
          "padding": "2px"
        }}>
            <div style={{
                "backgroundColor": "rgba(0, 0, 0, 0.3)",
                "marginTop": "0",
                "padding": "2px"
            }}>
                    <div style={{
                        "paddingLeft":"100px",
                        "display":"flex",
                        "alignItems":"center",
                        "justifyContent":"left"
                    }}>
                        <Image src={"/SLAX.png"} width={150} style={{
                        "marginRight":"60px"
                        }}/>
    

                        {links}
    
                    </div>
            </div>
        <div>
          {children}
        </div>
        </div>
      </div>
      </>

    )

}

export default Layout